name: Backend CI

on:
  push:
    paths:
      - 'hospital-backend-main/**'
  pull_request:
    paths:
      - 'hospital-backend-main/**'

jobs:
  build:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('hospital-backend-main/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build and run tests
        working-directory: hospital-backend-main
        run: |
          chmod +x mvnw
          ./mvnw -B test package
